apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ita.pvc.database.name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-failed
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ include "ita.pvc.database.size" . }}
