apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ita.ansible.deploy.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "ita.ansible.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "ita.ansible.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ include "ita.ansible.container.name" . }}
          image: {{ include "ita.ansible.container.image" . }}
          ports:
            - containerPort: 80
            - containerPort: 443
          securityContext:
            privileged: true
          volumeMounts:
            - name: exastro-file-volume
              mountPath: /exastro-file-volume
      volumes:
        - name: exastro-file-volume
          persistentVolumeClaim:
            claimName: {{ include "ita.pvc.file.name" . }}
