@startuml build-sequence

skinparam style strictuml

"GitHub\nActions\nworkflow" -> "Action\ncheckout@v2\n": (checkout source)
"GitHub\nActions\nworkflow" -> "\nmake\n": make build
"\nmake\n" -> "\ndocker\n": docker build
"\nmake\n" -> "\ndocker\n": docker run
"\nmake\n" -> "\ndocker\n": docker exec (preprocess)
"\nmake\n" -> "\ndocker\n": docker exec (install ITA)
"\nmake\n" -> "\ndocker\n": docker exec (postprocess)
"\nmake\n" -> "\ndocker\n": docker stop
"\nmake\n" -> "\ndocker\n": docker commit
"GitHub\nActions\nworkflow" -> "\nmake\n": make push
"\nmake\n" -> "\ndocker\n": docker login
"\ndocker\n" -> "GitHub\nContainer\nRegistry": (login)
"\nmake\n" -> "\ndocker\n": docker push
"\ndocker\n" -> "GitHub\nContainer\nRegistry": (upload image)
"GitHub\nActions\nworkflow" -> "\nmake\n": make evidence
"\nmake\n" -> "\ndocker\n": (collect evidence)
"GitHub\nActions\nworkflow" -> "Action\nupload-artifact@v2\n": (upload evidence)

@enduml