version: "3.9"
services:
  webapp:
    image: it-automation-webapp:1.7.2-centos8-ja
    privileged: true
    ports:
      - "8080:80"
    environment:
        EXASTRO_ITA_DB_HOST: database
    extra_hosts:
      - "exastro-it-automation:127.0.0.1"

  database:
    image: it-automation-mariadb:1.7.2-focal-ja
    environment:
      MARIADB_ROOT_PASSWORD: ita_db_root_password
      MARIADB_DATABASE: ita_db
