name: Build
on:
  workflow_dispatch:
    inputs:
      EXASTRO_ITA_VER:
        description: Version number
        required: true
        default: '1.9.1'
        
      EXASTRO_ITA_LANGS:
        description: Web UI Languages
        required: true
        default: '["ja", "en"]'

      DISTRO_SYMBOLS:
        description: Base image symbols
        required: true
        default: '["ubi8"]'

      EXASTRO_ITA_TYPES:
        description: Exastro IT Automation types
        required: true
        default: '["single, multi"]'

      # Example: https://github.com/exastro-suite/it-automation/archive/refs/heads/v1.9.1.tar.gz
      EXASTRO_ITA_INSTALLER_URL:
        description: Installer URL
        required: false

      # Example: it-automation-1.9.1
      EXASTRO_ITA_UNPACK_DIR_NAME:
        description: Installer unpack dir name
        required: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        EXASTRO_ITA_LANG: ${{ fromJSON(github.event.inputs.EXASTRO_ITA_LANGS) }}
        DISTRO_SYMBOL: ${{ fromJSON(github.event.inputs.DISTRO_SYMBOLS) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container image
        uses: ./.github/actions/build-container-image
        with:
          EXASTRO_ITA_IMAGE_NAME: it-automation
          EXASTRO_ITA_VER: ${{ github.event.inputs.EXASTRO_ITA_VER }}
          EXASTRO_ITA_LANG: ${{ matrix.EXASTRO_ITA_LANG }}
          DISTRO_SYMBOL: ${{ matrix.DISTRO_SYMBOL }}
          EXASTRO_ITA_INSTALLER_URL: ${{ github.event.inputs.EXASTRO_ITA_INSTALLER_URL }}
          EXASTRO_ITA_UNPACK_DIR_NAME: ${{ github.event.inputs.EXASTRO_ITA_UNPACK_DIR_NAME }}
