name: Build
on:
  workflow_dispatch:
    inputs:
      EXASTRO_ITA_VER:
        description: Version number
        required: true
        default: '1.11.2'

      EXASTRO_ITA_LANGS:
        description: Web UI Languages
        required: true
        default: '["ja", "en"]'

      DISTRO_SYMBOLS:
        description: Base image symbols
        required: true
        default: '["ubi8"]'

      EXASTRO_ITA_TYPES:
        description: Exastro IT Automation types
        required: true
        default: '["single, multi"]'

      # Example: https://github.com/exastro-suite/it-automation/archive/refs/heads/v1.11.0.tar.gz
      EXASTRO_ITA_INSTALLER_URL:
        description: Installer URL
        required: false

      # Example: it-automation-1.11.0
      EXASTRO_ITA_UNPACK_DIR_NAME:
        description: Installer unpack dir name
        required: false
jobs:
  set-image-names-single-type:
    name: Set image names for single type
    runs-on: ubuntu-latest
    outputs:
      image-names: ${{ steps.set-image-names.outputs.image-names }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image names
        id: set-image-names
        run: |
          IMAGE_NAMES=$(cat ${{ github.event.inputs.EXASTRO_ITA_VER }}/image-names-single-type.txt | jq -nRc '[inputs | select(length>0)]')
          echo "IMAGE_NAMES=${IMAGE_NAMES}"
          echo "image-names=${IMAGE_NAMES}" >> $GITHUB_OUTPUT

  build-single-type:
    name: Build single type
    runs-on: ubuntu-latest
    needs: set-image-names-single-type
    strategy:
      matrix:
        EXASTRO_ITA_IMAGE_NAME: ${{ fromJson(needs.set-image-names-single-type.outputs.image-names) }}
        EXASTRO_ITA_LANG: ${{ fromJSON(github.event.inputs.EXASTRO_ITA_LANGS) }}
        DISTRO_SYMBOL: ${{ fromJSON(github.event.inputs.DISTRO_SYMBOLS) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container image
        uses: ./.github/actions/build-container-image
        with:
          GITHUB_PAT: "${{ secrets.GITHUB_TOKEN }}"
          EXASTRO_ITA_IMAGE_NAME: ${{ matrix.EXASTRO_ITA_IMAGE_NAME }}
          EXASTRO_ITA_VER: ${{ github.event.inputs.EXASTRO_ITA_VER }}
          EXASTRO_ITA_LANG: ${{ matrix.EXASTRO_ITA_LANG }}
          DISTRO_SYMBOL: ${{ matrix.DISTRO_SYMBOL }}
          EXASTRO_ITA_INSTALLER_URL: ${{ github.event.inputs.EXASTRO_ITA_INSTALLER_URL }}
          EXASTRO_ITA_UNPACK_DIR_NAME: ${{ github.event.inputs.EXASTRO_ITA_UNPACK_DIR_NAME }}

  set-image-names-multi-type:
    name: Set image names for multi type
    runs-on: ubuntu-latest
    outputs:
      image-names: ${{ steps.set-image-names.outputs.image-names }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image names
        id: set-image-names
        run: |
          IMAGE_NAMES=$(cat ${{ github.event.inputs.EXASTRO_ITA_VER }}/image-names-multi-type.txt | jq -nRc '[inputs | select(length>0)]')
          echo "IMAGE_NAMES=${IMAGE_NAMES}"
          echo "image-names=${IMAGE_NAMES}" >> $GITHUB_OUTPUT

  build-multi-type:
    name: Build multi type
    runs-on: ubuntu-latest
    needs:
      - set-image-names-multi-type
      - build-single-type
    strategy:
      matrix:
        EXASTRO_ITA_IMAGE_NAME: ${{ fromJson(needs.set-image-names-multi-type.outputs.image-names) }}
        EXASTRO_ITA_LANG: ${{ fromJSON(github.event.inputs.EXASTRO_ITA_LANGS) }}
        DISTRO_SYMBOL: ${{ fromJSON(github.event.inputs.DISTRO_SYMBOLS) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container image
        uses: ./.github/actions/build-container-image
        with:
          GITHUB_PAT: "${{ secrets.GITHUB_TOKEN }}"
          EXASTRO_ITA_IMAGE_NAME: ${{ matrix.EXASTRO_ITA_IMAGE_NAME }}
          EXASTRO_ITA_VER: ${{ github.event.inputs.EXASTRO_ITA_VER }}
          EXASTRO_ITA_LANG: ${{ matrix.EXASTRO_ITA_LANG }}
          DISTRO_SYMBOL: ${{ matrix.DISTRO_SYMBOL }}
          EXASTRO_ITA_INSTALLER_URL: ${{ github.event.inputs.EXASTRO_ITA_INSTALLER_URL }}
          EXASTRO_ITA_UNPACK_DIR_NAME: ${{ github.event.inputs.EXASTRO_ITA_UNPACK_DIR_NAME }}
