apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-automation-webapp
  labels:
    app: it-automation-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-automation-webapp
  template:
    metadata:
      labels:
        app: it-automation-webapp
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "exastro-it-automation"
      containers:
        - name: {{ include "ita.webapp.containerName" . }}
          image: {{ include "ita.webapp.image" . }}
          envFrom:
            - configMapRef:
                name: it-automation-cm
            - prefix:
              secretRef:
                name: it-automation-secret
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - name: exastro-file-volume
              mountPath: /exastro-file-volume
      volumes:
        - name: exastro-file-volume
          persistentVolumeClaim:
            claimName: exastro-file-pvc
