apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ita.mariadb.deploy.name" . }}
  labels:
    app: it-automation-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-automation-mariadb
  template:
    metadata:
      labels:
        app: it-automation-mariadb
    spec:
      containers:
        - name: {{ include "ita.mariadb.container.name" . }}
          image: {{ include "ita.mariadb.container.image" . }}
          ports:
            - containerPort: 3306
          securityContext:
            privileged: true
          volumeMounts:
            - name: exastro-database-volume
              mountPath: /exastro-database-volume
      volumes:
        - name: exastro-database-volume
          persistentVolumeClaim:
            claimName: exastro-database-pvc