apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ita.ansible.deploy.name" . }}
  labels:
    app: it-automation-ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-automation-ansible
  template:
    metadata:
      labels:
        app: it-automation-ansible
    spec:
      containers:
        - name: {{ include "ita.ansible.container.name" . }}
          image: {{ include "ita.ansible.container.image" . }}
          ports:
            - containerPort: 80
            - containerPort: 443
          securityContext:
            privileged: true
          volumeMounts:
            - name: exastro-file-volume
              mountPath: /exastro-file-volume
      volumes:
        - name: exastro-file-volume
          persistentVolumeClaim:
            claimName: exastro-file-pvc