apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ita.backyard.deploy.name" . }}
  labels:
    app: it-automation-backyard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-automation-backyard
  template:
    metadata:
      labels:
        app: it-automation-backyard
    spec:
      containers:
        - name: {{ include "ita.backyard.container.name" . }}
          image: {{ include "ita.backyard.container.image" . }}
          envFrom:
            - configMapRef:
                name: {{ include "ita.cm.name" . }}
            - secretRef:
                name: {{ include "ita.secret.name" . }}
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - name: exastro-file-volume
              mountPath: /exastro-file-volume
      volumes:
        - name: exastro-file-volume
          persistentVolumeClaim:
            claimName: exastro-file-pvc